---
- name: Stand up development environment 
  hosts: localhost 
  tasks:
   - name: Update APT package manager  
     become: true
     apt:
       update_cache: yes
   
   - name: Install Java using Ansible
     become: true
     apt:
       name: openjdk-11-jdk
       state: present
   
   - name: Install Apache Maven
     become: true
     apt: 
       name: maven
       state: present
   
   - name: Install git
     become: true
     apt:
       name: git-all
       state: present

   - name: Prepare for installing docker
     become: true
     apt:
       pkg:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
       state: present

   - name: Run commands for docker
     become: true
     shell: |
       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
       echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
       sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

   - name: Install Docker CE
     become: true
     apt:
       update_cache: yes
       pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io
       state: present

   - name: Install Intellij
     become: true
     command: snap install intellij-idea-community --classic
