---
- name: Stand up development environment 
  hosts: localhost 
  tasks:
   - name: Update APT package manager  
     become: true
     apt:
       update_cache: yes
   
   - name: Install Java using Ansible
     become: true
     apt:
       name: openjdk-11-jdk
       state: present
   
   - name: Install Apache Maven
     become: true
     apt: 
       name: maven
       state: present
   
   - name: Install git
     become: true
     apt:
       name: git-all
       state: present
   
   - name: Install Intellij
     become: true
     command: snap install intellij-idea-community --classic
